### ISSUE TITLE
Hyperdeck Clip-Time & Timeline-Time Acting the Same

### ISSUE THREAD

**Issue by randallpacker** [SteffeyDev/atemOSC#231] opened 2021-09-15 16:58 UTC
Greetings: I just began experimenting with timeline-time, and it seems to act identical to clip-time. Assuming you're using the same messaging: 00:00:00 (hours-minutes-seconds) I only get timepoints within the current clip, unless the timepoint is greater than the current clip, and then it will jump to a longer clip that has that time. But it doesn't treat the timeline as one continuous timecode. 

Is there a refinement I am missing?

**Comment by SteffeyDev** [comment] 2021-09-16 02:59
Does the clip time behave the same way: when you set the clip time to a time longer than the current clip, does it jump to another clip? Or what does it do?

**Comment by randallpacker** [comment] 2021-09-16 16:29
It seems to do the following:
-- if the timepoint exists within the duration of the current clip, it goes there. 
-- if the timepoint is greater than the duration of the current clip, it goes to another clip where the timepoint exists
-- if the timepoint is greater than the duration of all of the clips, it doesn't go anywhere

This appears to be the same behavior is clip time, except that it jumps to another clip if it has the timepoint. 

My understanding is that time-line is supposed to treat all of the clips as one long duration, and jump to that point. I wonder if the timecode of the individual clips need to be continuous? 

Your thoughts?

**Comment by SteffeyDev** [comment] 2021-09-21 00:54
Ok.  I did check locally, and I am calling the correct underlying method (`SetCurrentTimelineTime` and not `SetCurrentClipTime`), so that means the issue is with the SDK itself, or the switcher.  I'll need to test it myself, and if I can reproduce I'll report the issue to BlackMagic

**Comment by randallpacker** [comment] 2021-09-21 01:15
Thanks Peter. I'll check it again and see if there is any chance I made an error, though I'm pretty sure I am using the right messaging. Randall

**Comment by SteffeyDev** [comment] 2021-11-12 05:00
@randallpacker I just got a Hyperdeck setup for testing, and I am unable to reproduce this issue.  I recorded two short clips, one 6 seconds followed by an 11 second clip.  When I set the timeline time to `00:00:08`, it jumps to the second clip, 2 seconds in.  If I then set the clip time to `00:00:04`, it stays in the second clip, but moves to 4 seconds in.  I tested this both while playing and while stopped.

> I wonder if the timecode of the individual clips need to be continuous?

Is there a way for individual clips to be not continuous on the timeline? I'm newer to HyperDecks, so maybe there's an edge case that you use frequently and I have not tested?

It is possible that this was a bug with the ATEM software itself, which was fixed in the 8.6.4 version, or some version between what you are running and 8.6.4

**Comment by randallpacker** [comment] 2021-11-12 15:06
Thanks Peter. Which version of atemOSC did you run your test with? I'll match that version up with ATEM 8.6.4 and see if it works for me.

**Comment by SteffeyDev** [comment] 2021-11-12 16:17
I was testing with the latest version (technically unreleased, but I haven't made any changes to the hyperdeck functionality since the last release)

**Comment by SteffeyDev** [comment] 2021-12-22 17:42
Ah, there's the edge case. Unfortunately I've never used Premiere or attempted to import clips to the hyperdeck, but editing them as one long clip might be a good solution. I haven't seen the import process, maybe there's a way to import them so that the hyperdeck fixes the timecodes as they come in? I'm not necessarily expecting that functionality, but it would be cool.

Im going to close this, as it's not an issue with atemOSC, but we can continue discussions after it's closed.

**Comment by randallpacker** [comment] 2021-12-22 17:47
Thanks Peter!! I have a very cool thing working in Max, where I am using clip-time $1 and send it random values within the duration of the clip, so I can randomly trigger frames. Not sure how fast I can do this but it is a great way to reshuffle a video.  Cheers and happy holidays!!

**Closed** 2022-01-12 00:16 UTC
