### ISSUE TITLE
/atem/send-status crashes atemOSC

### ISSUE THREAD

**Issue by chrisspiegl** [SteffeyDev/atemOSC#220] opened 2021-05-11 17:56 UTC
Hello, I was just trying to get the system to give me the status via `/atem/send-status` but that request crashes the atemOSC application.

The `/atem/me/1/send-status` on the other hand works.

With the generic `/atem/send-status` some messages are received, but not all? and as mentioned it then crashes.

I am on macOS and relatively new to this application, would love to get some feedback — especially if this is my error 🙈.

**Comment by SteffeyDev** [comment] 2021-06-19 02:07
Thanks, I haven't tested it for a while, probably just a bug. I'll look into it next time I'm working on this app.

**Comment by ales-michalek** [comment] 2021-10-02 20:37
Hello, Im having same trouble. Thank you! (old version of app 3.1.6 works)

**Comment by SteffeyDev** [comment] 2021-11-11 19:13
I was able to find the cause of the crash, this will be fixed in next release

**Comment by SteffeyDev** [comment] 2021-11-15 14:49
Released in 4.2.0, let me know if that doesn't fix it for you

**Closed by SteffeyDev** 2021-11-15 14:49 UTC
Labels: bug, pending-release
