### ISSUE TITLE
DVE position and Scale 

### ISSUE THREAD

**Issue by JonathanHouser** [SteffeyDev/atemOSC#217] opened 2021-04-22 18:38 UTC
Hey all. AtemOSC has really simplified my setup in an incredible way and I love that. One thing I would love to have is DVE Position X,Y and Scale, X,Y for my DVE pips. I know there already is a border command. Just would love to see that. Thanks for the great work!

Jonathan-

**Comment by SteffeyDev** [comment] 2021-04-24 17:19
Looks like this is duplicate of #176

**Closed by SteffeyDev** 2021-04-24 17:19 UTC
Labels: duplicate, new-feature
